### ISSUE TITLE
Question about your Liquidator 3D scans

### ISSUE THREAD

**Issue by eisnerguy1** [fgsfds/Liquidator-3D#9]
So, I found these scans on Mobygames:
https://www.mobygames.com/game/144799/liquidator/cover/group-256116/cover-652194/
https://www.mobygames.com/game/144799/liquidator/cover/group-256116/cover-652195/
https://www.mobygames.com/game/144799/liquidator/cover/group-256116/cover-652196/

It says you uploaded them back in 2020. Might you be able to share the original scan files?  I sent you a message on the Duke 4 forums and Mobygames as well. 

Thanks so much!

**Comment by fgsfds** [comment]
Can't find them, sorry
